name := 'claw-applet-calendar'
appid := 'com.clawos.PanelCalendarButton'
rootdir := ''
prefix := '/usr'
debug := '0'
target := if debug == '1' { 'debug' } else { 'release' }
targetdir := env('CARGO_TARGET_DIR', 'target')
bindir := rootdir + prefix + '/bin'
sharedir := rootdir + prefix + '/share'

default: build-release

build-debug *args:
    cargo build --locked {{ args }}

build-release *args: (build-debug '--release' args)

install:
    test -n "{{ rootdir }}" && stage="$(realpath -m -- "{{ rootdir }}")" && test "$stage" != /
    install -Dm0755 {{ targetdir }}/{{ target }}/{{ name }} {{ bindir }}/{{ name }}
    install -Dm0644 {{ targetdir }}/xdgen/{{ appid }}.desktop {{ sharedir }}/applications/{{ appid }}.desktop
    install -Dm0644 data/icons/scalable/actions/{{ appid }}-symbolic.svg {{ sharedir }}/icons/hicolor/scalable/actions/{{ appid }}-symbolic.svg
