use std::{env, fs, path::PathBuf};
use xdgen::{App, Context, FluentString};

fn main() {
    let ctx = Context::new("../i18n", env::var("CARGO_PKG_NAME").unwrap()).unwrap();

    [
        (
            "com.clawos.Settings",
            "app",
            "xdg-entry-comment",
            "xdg-entry-keywords",
        ),
        (
            "com.clawos.Settings.About",
            "xdg-entry-about",
            "xdg-entry-about-comment",
            "xdg-entry-about-keywords",
        ),
        (
            "com.clawos.Settings.Accessibility",
            "xdg-entry-ally",
            "xdg-entry-a11y-comment",
            "xdg-entry-a11y-keywords",
        ),
        (
            "com.clawos.Settings.Appearance",
            "appearance",
            "xdg-entry-appearance-comment",
            "xdg-entry-appearance-keywords",
        ),
        (
            "com.clawos.Settings.Applications",
            "xdg-entry-applications",
            "xdg-entry-applications-comment",
            "xdg-entry-applications-keywords",
        ),
        (
            "com.clawos.Settings.Bluetooth",
            "bluetooth",
            "xdg-entry-bluetooth-comment",
            "xdg-entry-bluetooth-keywords",
        ),
        (
            "com.clawos.Settings.DateTime",
            "xdg-entry-date-time",
            "xdg-entry-date-time-comment",
            "xdg-entry-date-time-keywords",
        ),
        (
            "com.clawos.Settings.DefaultApps",
            "xdg-entry-default-apps",
            "xdg-entry-default-apps-comment",
            "xdg-entry-default-apps-keywords",
        ),
        (
            "com.clawos.Settings.Desktop",
            "xdg-entry-desktop",
            "xdg-entry-desktop-comment",
            "xdg-entry-desktop-keywords",
        ),
        (
            "com.clawos.Settings.Displays",
            "xdg-entry-displays",
            "xdg-entry-displays-comment",
            "xdg-entry-displays-keywords",
        ),
        (
            "com.clawos.Settings.Dock",
            "xdg-entry-dock",
            "xdg-entry-dock-comment",
            "xdg-entry-dock-keywords",
        ),
        (
            "com.clawos.Settings.Input",
            "xdg-entry-input",
            "xdg-entry-input-comment",
            "xdg-entry-input-keywords",
        ),
        (
            "com.clawos.Settings.Keyboard",
            "xdg-entry-keyboard",
            "xdg-entry-keyboard-comment",
            "xdg-entry-keyboard-keywords",
        ),
        (
            "com.clawos.Settings.Mouse",
            "xdg-entry-mouse",
            "xdg-entry-mouse-comment",
            "xdg-entry-mouse-keywords",
        ),
        (
            "com.clawos.Settings.Network",
            "xdg-entry-network",
            "xdg-entry-network-comment",
            "xdg-entry-network-keywords",
        ),
        (
            "com.clawos.Settings.Notifications",
            "xdg-entry-notifications",
            "xdg-entry-notifications-comment",
            "xdg-entry-notifications-keywords",
        ),
        (
            "com.clawos.Settings.Panel",
            "xdg-entry-panel",
            "xdg-entry-panel-comment",
            "xdg-entry-panel-keywords",
        ),
        (
            "com.clawos.Settings.Power",
            "xdg-entry-power",
            "xdg-entry-power-comment",
            "xdg-entry-power-keywords",
        ),
        (
            "com.clawos.Settings.RegionLanguage",
            "xdg-entry-region-language",
            "xdg-entry-region-language-comment",
            "xdg-entry-region-language-keywords",
        ),
        (
            "com.clawos.Settings.Sound",
            "xdg-entry-sound",
            "xdg-entry-sound-comment",
            "xdg-entry-sound-keywords",
        ),
        (
            "com.clawos.Settings.StartupApps",
            "xdg-entry-startup-apps",
            "xdg-entry-startup-apps-comment",
            "xdg-entry-startup-apps-keywords",
        ),
        (
            "com.clawos.Settings.System",
            "xdg-entry-system",
            "xdg-entry-system-comment",
            "xdg-entry-system-keywords",
        ),
        (
            "com.clawos.Settings.Time",
            "xdg-entry-time-language",
            "xdg-entry-time-language-comment",
            "xdg-entry-time-language-keywords",
        ),
        (
            "com.clawos.Settings.Touchpad",
            "xdg-entry-touchpad",
            "xdg-entry-touchpad-comment",
            "xdg-entry-touchpad-keywords",
        ),
        (
            "com.clawos.Settings.Users",
            "xdg-entry-users",
            "xdg-entry-users-comment",
            "xdg-entry-users-keywords",
        ),
        (
            "com.clawos.Settings.Vpn",
            "vpn",
            "xdg-entry-vpn-comment",
            "xdg-entry-vpn-keywords",
        ),
        (
            "com.clawos.Settings.Wallpaper",
            "xdg-entry-wallpaper",
            "xdg-entry-wallpaper-comment",
            "xdg-entry-wallpaper-keywords",
        ),
        (
            "com.clawos.Settings.WindowManagement",
            "xdg-entry-window-management",
            "xdg-entry-window-management-comment",
            "xdg-entry-window-management-keywords",
        ),
        (
            "com.clawos.Settings.Wired",
            "xdg-entry-wired",
            "xdg-entry-wired-comment",
            "xdg-entry-wired-keywords",
        ),
        (
            "com.clawos.Settings.Wireless",
            "xdg-entry-wireless",
            "xdg-entry-wireless-comment",
            "xdg-entry-wireless-keywords",
        ),
        (
            "com.clawos.Settings.Workspaces",
            "xdg-entry-workspaces",
            "xdg-entry-workspaces-comment",
            "xdg-entry-workspaces-keywords",
        ),
        (
            "com.clawos.Settings.LegacyApplications",
            "xdg-entry-x11-applications",
            "xdg-entry-x11-applications-comment",
            "xdg-entry-x11-applications-keywords",
        ),
    ]
    .into_iter()
    .map(|(id, name, comment, keywords)| {
        let app = App::new(FluentString(name))
            .comment(FluentString(comment))
            .keywords(FluentString(keywords));

        let output = PathBuf::from("../target/xdgen");

        (id, app, output)
    })
    .for_each(|(id, app, output)| {
        fs::create_dir_all(&output).unwrap();
        fs::write(
            output.join(format!("{}.desktop", id)),
            app.expand_desktop(
                dbg!(format!("../resources/applications/{}.desktop", id)),
                &ctx,
            )
            .unwrap(),
        )
        .unwrap();
    });
}
